--
-- PostgreSQL database dump
--

\restrict XDdX7XXo6riaJaum8nGwr0o4kNrdDfv6GVz24eqg8ZFwX99wqX4mJD6mKW1aznz

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Debian 16.11-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: answers; Type: TABLE; Schema: public; Owner: tomzxy
--

CREATE TABLE public.answers (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    uuid character varying(255) NOT NULL,
    answer_correct boolean NOT NULL,
    answer_name character varying(500) NOT NULL,
    answer_type character varying(20) NOT NULL,
    question_id bigint NOT NULL,
    CONSTRAINT answers_answer_type_check CHECK (((answer_type)::text = ANY ((ARRAY['TEXT'::character varying, 'IMAGE'::character varying])::text[])))
);


ALTER TABLE public.answers OWNER TO tomzxy;

--
-- Name: answers_id_seq; Type: SEQUENCE; Schema: public; Owner: tomzxy
--

ALTER TABLE public.answers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.answers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: folder; Type: TABLE; Schema: public; Owner: tomzxy
--

CREATE TABLE public.folder (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    uuid character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    bank_id bigint NOT NULL,
    parent_id bigint
);


ALTER TABLE public.folder OWNER TO tomzxy;

--
-- Name: folder_id_seq; Type: SEQUENCE; Schema: public; Owner: tomzxy
--

ALTER TABLE public.folder ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.folder_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lobbies; Type: TABLE; Schema: public; Owner: tomzxy
--

CREATE TABLE public.lobbies (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    uuid character varying(255) NOT NULL,
    code_invite character varying(255),
    lobby_name character varying(255),
    host_id bigint
);


ALTER TABLE public.lobbies OWNER TO tomzxy;

--
-- Name: lobbies_id_seq; Type: SEQUENCE; Schema: public; Owner: tomzxy
--

ALTER TABLE public.lobbies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lobbies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lobby_members; Type: TABLE; Schema: public; Owner: tomzxy
--

CREATE TABLE public.lobby_members (
    joined_at timestamp(6) without time zone,
    role character varying(255),
    lobby_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT lobby_members_role_check CHECK (((role)::text = ANY ((ARRAY['HOST'::character varying, 'MEMBER'::character varying])::text[])))
);


ALTER TABLE public.lobby_members OWNER TO tomzxy;

--
-- Name: notifications; Type: TABLE; Schema: public; Owner: tomzxy
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    uuid character varying(255) NOT NULL,
    content text,
    title character varying(255),
    type character varying(255),
    user_id bigint,
    lobby_id bigint,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['SYSTEM'::character varying, 'GROUP'::character varying, 'PERSONAL'::character varying])::text[])))
);


ALTER TABLE public.notifications OWNER TO tomzxy;

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: tomzxy
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permission; Type: TABLE; Schema: public; Owner: tomzxy
--

CREATE TABLE public.permission (
    permission_name character varying(255) NOT NULL,
    description character varying(255),
    is_active boolean NOT NULL
);


ALTER TABLE public.permission OWNER TO tomzxy;

--
-- Name: question_banks; Type: TABLE; Schema: public; Owner: tomzxy
--

CREATE TABLE public.question_banks (
    owner_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    uuid character varying(255) NOT NULL
);


ALTER TABLE public.question_banks OWNER TO tomzxy;

--
-- Name: questions; Type: TABLE; Schema: public; Owner: tomzxy
--

CREATE TABLE public.questions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    uuid character varying(255) NOT NULL,
    content_hash character varying(64) NOT NULL,
    level character varying(20),
    question_name character varying(1000) NOT NULL,
    question_type character varying(20) NOT NULL,
    bank_id bigint,
    folder_id bigint,
    CONSTRAINT questions_level_check CHECK (((level)::text = ANY ((ARRAY['EASY'::character varying, 'MEDIUM'::character varying, 'HARD'::character varying])::text[]))),
    CONSTRAINT questions_question_type_check CHECK (((question_type)::text = ANY ((ARRAY['TEXT'::character varying, 'IMAGE'::character varying])::text[])))
);


ALTER TABLE public.questions OWNER TO tomzxy;

--
-- Name: questions_id_seq; Type: SEQUENCE; Schema: public; Owner: tomzxy
--

ALTER TABLE public.questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quiz_instances; Type: TABLE; Schema: public; Owner: tomzxy
--

CREATE TABLE public.quiz_instances (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    uuid character varying(255) NOT NULL,
    answers_snapshot jsonb,
    earned_points bigint NOT NULL,
    ended_at timestamp(6) without time zone,
    snapshot jsonb,
    started_at timestamp(6) without time zone NOT NULL,
    status character varying(20) NOT NULL,
    total_points bigint NOT NULL,
    quiz_id bigint NOT NULL,
    user_id bigint,
    CONSTRAINT quiz_instances_status_check CHECK (((status)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'SUBMITTED'::character varying, 'TIMED_OUT'::character varying, 'ABANDONED'::character varying])::text[])))
);


ALTER TABLE public.quiz_instances OWNER TO tomzxy;

--
-- Name: quiz_instances_id_seq; Type: SEQUENCE; Schema: public; Owner: tomzxy
--

ALTER TABLE public.quiz_instances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_instances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quiz_question_links; Type: TABLE; Schema: public; Owner: tomzxy
--

CREATE TABLE public.quiz_question_links (
    points bigint NOT NULL,
    quiz_id bigint NOT NULL,
    question_id bigint NOT NULL
);


ALTER TABLE public.quiz_question_links OWNER TO tomzxy;

--
-- Name: quiz_user_responses; Type: TABLE; Schema: public; Owner: tomzxy
--

CREATE TABLE public.quiz_user_responses (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    uuid character varying(255) NOT NULL,
    answered_at timestamp(6) without time zone,
    is_correct boolean NOT NULL,
    is_skipped boolean NOT NULL,
    points_earned bigint NOT NULL,
    question_id bigint NOT NULL,
    question_snapshot_key character varying(255),
    response_time_seconds integer,
    selected_answer_id bigint,
    selected_answer_ids jsonb,
    quiz_instance_id bigint NOT NULL
);


ALTER TABLE public.quiz_user_responses OWNER TO tomzxy;

--
-- Name: quiz_user_responses_id_seq; Type: SEQUENCE; Schema: public; Owner: tomzxy
--

ALTER TABLE public.quiz_user_responses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_user_responses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quizzes; Type: TABLE; Schema: public; Owner: tomzxy
--

CREATE TABLE public.quizzes (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    uuid character varying(255) NOT NULL,
    config jsonb,
    description character varying(1000),
    end_date timestamp(6) without time zone,
    max_attempt integer,
    question_layout jsonb,
    start_date timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    time_limit_minutes integer,
    title character varying(200) NOT NULL,
    visibility character varying(255),
    host_id bigint NOT NULL,
    lobby_id bigint,
    subject_id bigint NOT NULL,
    CONSTRAINT quizzes_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'OPENED'::character varying, 'PAUSED'::character varying, 'CLOSED'::character varying, 'ARCHIVED'::character varying])::text[]))),
    CONSTRAINT quizzes_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['PUBLIC'::character varying, 'PRIVATE'::character varying, 'CLASS_ONLY'::character varying])::text[])))
);


ALTER TABLE public.quizzes OWNER TO tomzxy;

--
-- Name: quizzes_id_seq; Type: SEQUENCE; Schema: public; Owner: tomzxy
--

ALTER TABLE public.quizzes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quizzes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: tomzxy
--

CREATE TABLE public.refresh_tokens (
    id uuid NOT NULL,
    device_id character varying(100),
    device_name character varying(100),
    expired_at timestamp(6) with time zone NOT NULL,
    ip_address character varying(100),
    issued_at timestamp(6) with time zone NOT NULL,
    jti character varying(36) NOT NULL,
    last_used_at timestamp(6) with time zone,
    revoked boolean NOT NULL,
    user_agent character varying(500),
    user_id bigint NOT NULL
);


ALTER TABLE public.refresh_tokens OWNER TO tomzxy;

--
-- Name: role; Type: TABLE; Schema: public; Owner: tomzxy
--

CREATE TABLE public.role (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    uuid character varying(255) NOT NULL,
    name character varying(255)
);


ALTER TABLE public.role OWNER TO tomzxy;

--
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: tomzxy
--

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role_permission_object; Type: TABLE; Schema: public; Owner: tomzxy
--

CREATE TABLE public.role_permission_object (
    object_type character varying(255) NOT NULL,
    permission_name character varying(255) NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.role_permission_object OWNER TO tomzxy;

--
-- Name: subject; Type: TABLE; Schema: public; Owner: tomzxy
--

CREATE TABLE public.subject (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    uuid character varying(255) NOT NULL,
    description character varying(255),
    subject_name character varying(255)
);


ALTER TABLE public.subject OWNER TO tomzxy;

--
-- Name: subject_id_seq; Type: SEQUENCE; Schema: public; Owner: tomzxy
--

ALTER TABLE public.subject ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_notifications; Type: TABLE; Schema: public; Owner: tomzxy
--

CREATE TABLE public.user_notifications (
    is_read boolean NOT NULL,
    read_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    notification_id bigint NOT NULL
);


ALTER TABLE public.user_notifications OWNER TO tomzxy;

--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: tomzxy
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.user_roles OWNER TO tomzxy;

--
-- Name: users; Type: TABLE; Schema: public; Owner: tomzxy
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    uuid character varying(255) NOT NULL,
    email character varying(100) NOT NULL,
    is_email_verified boolean NOT NULL,
    last_login_at timestamp(6) without time zone,
    password_hash character varying(255) NOT NULL,
    profile_picture_url character varying(500),
    user_name character varying(50) NOT NULL
);


ALTER TABLE public.users OWNER TO tomzxy;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: tomzxy
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: answers answers_pkey; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.answers
    ADD CONSTRAINT answers_pkey PRIMARY KEY (id);


--
-- Name: folder folder_pkey; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.folder
    ADD CONSTRAINT folder_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens idx_jti; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT idx_jti UNIQUE (jti);


--
-- Name: lobbies lobbies_pkey; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.lobbies
    ADD CONSTRAINT lobbies_pkey PRIMARY KEY (id);


--
-- Name: lobby_members lobby_members_pkey; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.lobby_members
    ADD CONSTRAINT lobby_members_pkey PRIMARY KEY (lobby_id, user_id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: permission permission_pkey; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT permission_pkey PRIMARY KEY (permission_name);


--
-- Name: question_banks question_banks_pkey; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.question_banks
    ADD CONSTRAINT question_banks_pkey PRIMARY KEY (owner_id);


--
-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (id);


--
-- Name: quiz_instances quiz_instances_pkey; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.quiz_instances
    ADD CONSTRAINT quiz_instances_pkey PRIMARY KEY (id);


--
-- Name: quiz_question_links quiz_question_links_pkey; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.quiz_question_links
    ADD CONSTRAINT quiz_question_links_pkey PRIMARY KEY (question_id, quiz_id);


--
-- Name: quiz_user_responses quiz_user_responses_pkey; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.quiz_user_responses
    ADD CONSTRAINT quiz_user_responses_pkey PRIMARY KEY (id);


--
-- Name: quizzes quizzes_pkey; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.quizzes
    ADD CONSTRAINT quizzes_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: role_permission_object role_permission_object_pkey; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.role_permission_object
    ADD CONSTRAINT role_permission_object_pkey PRIMARY KEY (object_type, permission_name, role_id);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- Name: subject subject_pkey; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.subject
    ADD CONSTRAINT subject_pkey PRIMARY KEY (id);


--
-- Name: questions uk22uvhsu2cnsb404orqsl6gqdh; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT uk22uvhsu2cnsb404orqsl6gqdh UNIQUE (content_hash);


--
-- Name: answers uk412ifc72yywh3y0lq6h9o20rf; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.answers
    ADD CONSTRAINT uk412ifc72yywh3y0lq6h9o20rf UNIQUE (uuid);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users uk6km2m9i3vjuy36rnvkgj1l61s; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6km2m9i3vjuy36rnvkgj1l61s UNIQUE (uuid);


--
-- Name: lobbies uk6qw1rhcg8qn511fp0rau80dh7; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.lobbies
    ADD CONSTRAINT uk6qw1rhcg8qn511fp0rau80dh7 UNIQUE (uuid);


--
-- Name: subject uk8qyfrjxvnyg18qw2l6nmu3umt; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.subject
    ADD CONSTRAINT uk8qyfrjxvnyg18qw2l6nmu3umt UNIQUE (uuid);


--
-- Name: quiz_user_responses uk_instance_question; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.quiz_user_responses
    ADD CONSTRAINT uk_instance_question UNIQUE (quiz_instance_id, question_id);


--
-- Name: quiz_instances uk_quiz_user_inprogress; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.quiz_instances
    ADD CONSTRAINT uk_quiz_user_inprogress UNIQUE (quiz_id, user_id, status);


--
-- Name: role ukk5dwya5n8n7y3m2opvmm7qjcc; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT ukk5dwya5n8n7y3m2opvmm7qjcc UNIQUE (uuid);


--
-- Name: users ukk8d0f2n7n88w1a16yhua64onx; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukk8d0f2n7n88w1a16yhua64onx UNIQUE (user_name);


--
-- Name: notifications ukm87yc1ihr2v3wl91w4i9issny; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT ukm87yc1ihr2v3wl91w4i9issny UNIQUE (uuid);


--
-- Name: folder ukmown42ajxvvjivj4gldxonoax; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.folder
    ADD CONSTRAINT ukmown42ajxvvjivj4gldxonoax UNIQUE (uuid);


--
-- Name: quiz_user_responses ukmpituim3g6osav34tdm5s1ekm; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.quiz_user_responses
    ADD CONSTRAINT ukmpituim3g6osav34tdm5s1ekm UNIQUE (uuid);


--
-- Name: questions uknhs7x0aa4xjreccx7wpo0bc45; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT uknhs7x0aa4xjreccx7wpo0bc45 UNIQUE (uuid);


--
-- Name: question_banks uknpg8poba270e8iosqw9f6igsf; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.question_banks
    ADD CONSTRAINT uknpg8poba270e8iosqw9f6igsf UNIQUE (uuid);


--
-- Name: quiz_instances ukobqal28rlt1plyfe68k7u76ig; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.quiz_instances
    ADD CONSTRAINT ukobqal28rlt1plyfe68k7u76ig UNIQUE (uuid);


--
-- Name: quizzes ukqr0ox06pyqico8cvwbk3h8ljs; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.quizzes
    ADD CONSTRAINT ukqr0ox06pyqico8cvwbk3h8ljs UNIQUE (uuid);


--
-- Name: user_notifications user_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.user_notifications
    ADD CONSTRAINT user_notifications_pkey PRIMARY KEY (notification_id, user_id);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_answer_correct; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_answer_correct ON public.answers USING btree (answer_correct);


--
-- Name: idx_answer_question; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_answer_question ON public.answers USING btree (question_id);


--
-- Name: idx_bank_owner; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_bank_owner ON public.question_banks USING btree (owner_id);


--
-- Name: idx_expired_at; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_expired_at ON public.refresh_tokens USING btree (expired_at);


--
-- Name: idx_lobby_member_lobby; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_lobby_member_lobby ON public.lobby_members USING btree (lobby_id);


--
-- Name: idx_lobby_member_lobby_user; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_lobby_member_lobby_user ON public.lobby_members USING btree (lobby_id, user_id);


--
-- Name: idx_lobby_member_user; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_lobby_member_user ON public.lobby_members USING btree (user_id);


--
-- Name: idx_question_bank; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_question_bank ON public.questions USING btree (bank_id);


--
-- Name: idx_question_bank_folder; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_question_bank_folder ON public.questions USING btree (bank_id, folder_id);


--
-- Name: idx_question_created_at; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_question_created_at ON public.questions USING btree (created_at);


--
-- Name: idx_question_folder; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_question_folder ON public.questions USING btree (folder_id);


--
-- Name: idx_question_level; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_question_level ON public.questions USING btree (level);


--
-- Name: idx_question_type; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_question_type ON public.questions USING btree (question_type);


--
-- Name: idx_quiz_created_at; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_quiz_created_at ON public.quizzes USING btree (created_at);


--
-- Name: idx_quiz_host; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_quiz_host ON public.quizzes USING btree (host_id);


--
-- Name: idx_quiz_instance_quiz; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_quiz_instance_quiz ON public.quiz_instances USING btree (quiz_id);


--
-- Name: idx_quiz_instance_started; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_quiz_instance_started ON public.quiz_instances USING btree (started_at);


--
-- Name: idx_quiz_instance_user; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_quiz_instance_user ON public.quiz_instances USING btree (user_id);


--
-- Name: idx_quiz_subject; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_quiz_subject ON public.quizzes USING btree (subject_id);


--
-- Name: idx_quiz_user_response_instance; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_quiz_user_response_instance ON public.quiz_user_responses USING btree (quiz_instance_id);


--
-- Name: idx_quiz_user_response_instance_answered; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_quiz_user_response_instance_answered ON public.quiz_user_responses USING btree (quiz_instance_id, answered_at);


--
-- Name: idx_quiz_user_response_instance_correct; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_quiz_user_response_instance_correct ON public.quiz_user_responses USING btree (quiz_instance_id, is_correct);


--
-- Name: idx_quiz_user_status; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_quiz_user_status ON public.quiz_instances USING btree (quiz_id, user_id, status);


--
-- Name: idx_quiz_visibility; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_quiz_visibility ON public.quizzes USING btree (visibility);


--
-- Name: idx_user_email; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_user_email ON public.users USING btree (email);


--
-- Name: idx_user_id; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_user_id ON public.refresh_tokens USING btree (user_id);


--
-- Name: idx_user_roles_role_id; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_user_roles_role_id ON public.user_roles USING btree (role_id);


--
-- Name: idx_user_roles_user_id; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_user_roles_user_id ON public.user_roles USING btree (user_id);


--
-- Name: idx_user_username; Type: INDEX; Schema: public; Owner: tomzxy
--

CREATE INDEX idx_user_username ON public.users USING btree (user_name);


--
-- Name: refresh_tokens fk1lih5y2npsf8u5o3vhdb9y0os; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: answers fk3erw1a3t0r78st8ty27x6v3g1; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.answers
    ADD CONSTRAINT fk3erw1a3t0r78st8ty27x6v3g1 FOREIGN KEY (question_id) REFERENCES public.questions(id);


--
-- Name: quiz_instances fk3gu68kfy7mebise22jhhlulrw; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.quiz_instances
    ADD CONSTRAINT fk3gu68kfy7mebise22jhhlulrw FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: folder fk6v3m3iyogdnix80g1btief7y; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.folder
    ADD CONSTRAINT fk6v3m3iyogdnix80g1btief7y FOREIGN KEY (bank_id) REFERENCES public.question_banks(owner_id);


--
-- Name: question_banks fk7gwo94ifvmd9gcftuxqt9ugeh; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.question_banks
    ADD CONSTRAINT fk7gwo94ifvmd9gcftuxqt9ugeh FOREIGN KEY (owner_id) REFERENCES public.users(id);


--
-- Name: quizzes fk8usn959vod7g5aujcjt3mxa1m; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.quizzes
    ADD CONSTRAINT fk8usn959vod7g5aujcjt3mxa1m FOREIGN KEY (host_id) REFERENCES public.users(id);


--
-- Name: user_notifications fk9f86wonnl11hos1cuf5fibutl; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.user_notifications
    ADD CONSTRAINT fk9f86wonnl11hos1cuf5fibutl FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: notifications fk9y21adhxn0ayjhfocscqox7bh; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: quiz_question_links fka25q7nsyyvcmv35j9m9u8cbed; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.quiz_question_links
    ADD CONSTRAINT fka25q7nsyyvcmv35j9m9u8cbed FOREIGN KEY (quiz_id) REFERENCES public.quizzes(id);


--
-- Name: questions fkab3qxet4lhtxl7x8ydifoslw5; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT fkab3qxet4lhtxl7x8ydifoslw5 FOREIGN KEY (folder_id) REFERENCES public.folder(id);


--
-- Name: quiz_question_links fkapn67meo3ccvc42u4me4ax4ys; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.quiz_question_links
    ADD CONSTRAINT fkapn67meo3ccvc42u4me4ax4ys FOREIGN KEY (question_id) REFERENCES public.questions(id);


--
-- Name: lobby_members fkbwr8wkd8alblvj0f3o4gbqno; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.lobby_members
    ADD CONSTRAINT fkbwr8wkd8alblvj0f3o4gbqno FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: role_permission_object fkcjh8wvsyt2v1g8cpnxn2hndw0; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.role_permission_object
    ADD CONSTRAINT fkcjh8wvsyt2v1g8cpnxn2hndw0 FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- Name: questions fkep9feemoosshrpb95idh0xw1q; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT fkep9feemoosshrpb95idh0xw1q FOREIGN KEY (bank_id) REFERENCES public.question_banks(owner_id);


--
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: quizzes fkk3pmfnkimtfaxsg0ag8id7i92; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.quizzes
    ADD CONSTRAINT fkk3pmfnkimtfaxsg0ag8id7i92 FOREIGN KEY (subject_id) REFERENCES public.subject(id);


--
-- Name: quiz_user_responses fkkmm3o28nuv4oo9c6xypgflswm; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.quiz_user_responses
    ADD CONSTRAINT fkkmm3o28nuv4oo9c6xypgflswm FOREIGN KEY (quiz_instance_id) REFERENCES public.quiz_instances(id);


--
-- Name: lobbies fkku0xjuv3yydatips0sn2cb3ji; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.lobbies
    ADD CONSTRAINT fkku0xjuv3yydatips0sn2cb3ji FOREIGN KEY (host_id) REFERENCES public.users(id);


--
-- Name: folder fkn0cjh1seljcp0mc4tj1ufh99m; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.folder
    ADD CONSTRAINT fkn0cjh1seljcp0mc4tj1ufh99m FOREIGN KEY (parent_id) REFERENCES public.folder(id);


--
-- Name: role_permission_object fkn8j79mscvpa505tdi8du1bpul; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.role_permission_object
    ADD CONSTRAINT fkn8j79mscvpa505tdi8du1bpul FOREIGN KEY (permission_name) REFERENCES public.permission(permission_name);


--
-- Name: quiz_instances fknhhnbogiy0laqial2xgwrxgbx; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.quiz_instances
    ADD CONSTRAINT fknhhnbogiy0laqial2xgwrxgbx FOREIGN KEY (quiz_id) REFERENCES public.quizzes(id);


--
-- Name: user_notifications fkovvx0ab3h8s9lrm6fppuadn7d; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.user_notifications
    ADD CONSTRAINT fkovvx0ab3h8s9lrm6fppuadn7d FOREIGN KEY (notification_id) REFERENCES public.notifications(id);


--
-- Name: notifications fkpn271v0upg7aqfwpu0j0i3n9o; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fkpn271v0upg7aqfwpu0j0i3n9o FOREIGN KEY (lobby_id) REFERENCES public.lobbies(id);


--
-- Name: lobby_members fkq5xry04b8nincqy0unxcsjus5; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.lobby_members
    ADD CONSTRAINT fkq5xry04b8nincqy0unxcsjus5 FOREIGN KEY (lobby_id) REFERENCES public.lobbies(id);


--
-- Name: quizzes fkqjy15pked6p13vkt18ivevbc7; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.quizzes
    ADD CONSTRAINT fkqjy15pked6p13vkt18ivevbc7 FOREIGN KEY (lobby_id) REFERENCES public.lobbies(id);


--
-- Name: user_roles fkrhfovtciq1l558cw6udg0h0d3; Type: FK CONSTRAINT; Schema: public; Owner: tomzxy
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkrhfovtciq1l558cw6udg0h0d3 FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- PostgreSQL database dump complete
--

\unrestrict XDdX7XXo6riaJaum8nGwr0o4kNrdDfv6GVz24eqg8ZFwX99wqX4mJD6mKW1aznz

