spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

logging:
  level:
    com.tomzxy.web_quiz: DEBUG
    org.springframework.security: DEBUG

jwt:
  secret: ${JWT_SECRET}

groq:
  api-key: ${GROQ_KEY}