
tomzxy.openapi.dev-url=http://localhost:8080
tomzxy.openapi.prod-url=https://tomzxy-api.com
springdoc.packages-to-scan=com.tomzxy.web_quiz.controllers
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG


