

# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/kieunu?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=datvip2003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG

#spring.devtools.restart.enabled=true
#spring.devtools.livereload.enabled=true




tomzxy.openapi.dev-url=http://localhost:8080
tomzxy.openapi.prod-url=https://tomzxy-api.com
springdoc.packages-to-scan=com.tomzxy.web_quiz.controllers


