CREATE TABLE public.users (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6),
    uuid varchar(255) NOT NULL UNIQUE,
    email varchar(100) NOT NULL UNIQUE,
    is_email_verified boolean NOT NULL,
    last_login_at timestamp(6),
    password_hash varchar(255) NOT NULL,
    profile_picture_url varchar(500),
    user_name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE public.subject (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6),
    uuid varchar(255) NOT NULL UNIQUE,
    description varchar(255),
    subject_name varchar(255)
);

CREATE TABLE public.quizzes (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6),
    uuid varchar(255) NOT NULL UNIQUE,
    config jsonb,
    description varchar(1000),
    end_date timestamp(6),
    max_attempt integer CHECK (max_attempt > 0),
    total_questions integer,
    question_layout jsonb,
    start_date timestamp(6),
    status varchar(255) NOT NULL CHECK (status IN ('DRAFT', 'OPENED', 'PAUSED', 'CLOSED', 'ARCHIVED')),
    time_limit_minutes integer CHECK (time_limit_minutes >= 0),
    title varchar(200) NOT NULL,
    visibility varchar(255) CHECK (visibility IN ('PUBLIC', 'PRIVATE', 'CLASS_ONLY')),
    host_id bigint NOT NULL,
    lobby_id bigint,
    subject_id bigint NOT NULL
);

CREATE TABLE public.questions (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6),
    uuid varchar(255) NOT NULL UNIQUE,
    content_hash varchar(64) NOT NULL UNIQUE,
    level varchar(20) CHECK (level IN ('EASY', 'MEDIUM', 'HARD')),
    question_name varchar(1000) NOT NULL,
    question_type varchar(20) NOT NULL CHECK (question_type IN ('TEXT', 'IMAGE')),
    bank_id bigint,
    folder_id bigint,
    subject_id bigint -- Bổ sung để khớp với logic môn học
);

CREATE TABLE public.answers (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6),
    uuid varchar(255) NOT NULL UNIQUE,
    answer_correct boolean NOT NULL,
    answer_name varchar(500) NOT NULL,
    answer_type varchar(20) NOT NULL CHECK (answer_type IN ('TEXT', 'IMAGE')),
    question_id bigint NOT NULL
);

CREATE TABLE public.quiz_instances (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6),
    uuid varchar(255) NOT NULL UNIQUE,
    guest_id varchar(255),
    answers_snapshot jsonb,
    earned_points bigint NOT NULL DEFAULT 0,
    ended_at timestamp(6),
    snapshot jsonb,
    started_at timestamp(6) NOT NULL,
    status varchar(20) NOT NULL CHECK (status IN ('IN_PROGRESS', 'SUBMITTED', 'TIMED_OUT', 'ABANDONED')),
    total_points bigint NOT NULL DEFAULT 0,
    quiz_id bigint NOT NULL,
    user_id bigint
);

CREATE TABLE public.quiz_user_responses (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6),
    uuid varchar(255) NOT NULL UNIQUE,
    answered_at timestamp(6),
    is_correct boolean NOT NULL,
    is_skipped boolean NOT NULL,
    points_earned bigint NOT NULL,
    question_id bigint,
    question_snapshot_key varchar(255),
    response_time_seconds integer,
    selected_answer_id bigint,
    selected_answer_ids jsonb,
    quiz_instance_id bigint NOT NULL
);

-- Question Banks table
CREATE TABLE public.question_banks (
    owner_id bigint NOT NULL,
    created_at timestamp(6) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6),
    uuid varchar(255) NOT NULL UNIQUE,
    PRIMARY KEY (owner_id)
);

-- Folder table for hierarchical question organization
CREATE TABLE public.folder (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6),
    uuid varchar(255) NOT NULL UNIQUE,
    name varchar(255) NOT NULL,
    bank_id bigint NOT NULL,
    parent_id bigint
);

-- Lobbies (Groups) table
CREATE TABLE public.lobbies (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6),
    uuid varchar(255) NOT NULL UNIQUE,
    lobby_name varchar(255),
    host_id bigint,
    code_invite varchar(20) NOT NULL UNIQUE
);

-- Lobby Members junction table
CREATE TABLE public.lobby_members (
    lobby_id bigint NOT NULL,
    user_id bigint NOT NULL,
    joined_at timestamp(6),
    role varchar(50) NOT NULL CHECK (role IN ('HOST', 'MEMBER')),
    PRIMARY KEY (lobby_id, user_id)
);

-- Role table
CREATE TABLE public.role (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6),
    uuid varchar(255) NOT NULL UNIQUE,
    name varchar(50) NOT NULL UNIQUE
);

-- Permission table
CREATE TABLE public.permission (
    permission_name varchar(50) NOT NULL PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6),
    uuid varchar(255) NOT NULL UNIQUE,
    description varchar(255)
);

-- Role Permission Object (junction table)
CREATE TABLE public.role_permission_object (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6),
    uuid varchar(255) NOT NULL UNIQUE,
    role_id bigint NOT NULL,
    permission_name varchar(50) NOT NULL,
    object_type varchar(50) NOT NULL
);

-- User Roles junction table
CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

-- Notifications table
CREATE TABLE public.notifications (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6),
    uuid varchar(255) NOT NULL UNIQUE,
    title varchar(255),
    message varchar(1000),
    type varchar(50),
    user_id bigint,
    lobby_id bigint
);

-- User Notifications junction table
CREATE TABLE public.user_notifications (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6),
    uuid varchar(255) NOT NULL UNIQUE,
    user_id bigint NOT NULL,
    notification_id bigint NOT NULL,
    is_read boolean DEFAULT false
);

-- Refresh Tokens table
CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp(6),
    uuid varchar(255) NOT NULL UNIQUE,
    jti varchar(255) NOT NULL UNIQUE,
    user_id bigint NOT NULL,
    issued_at timestamp(6),
    expired_at timestamp(6),
    last_used_at timestamp(6),
    revoked boolean DEFAULT false,
    device_id varchar(255),
    device_name varchar(255),
    ip_address varchar(45),
    user_agent varchar(500)
);

-- Quiz Question Links (junction table)
CREATE TABLE public.quiz_question_links (
    quiz_id bigint NOT NULL,
    question_id bigint NOT NULL,
    points integer,
    display_order integer,
    PRIMARY KEY (quiz_id, question_id)
);